version: '3'

services:
  mysql:
    build:
      context: ./dockerfiles/mysql
    environment:
      - TZ=${TZ}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ${MYSQL_SQL_FILE}:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "${MYSQL_PORT}:3306"
    restart: always
  
  redis:
    build:
      context: ./dockerfiles/redis
    environment:
      - TZ=${TZ}
    volumes:
      - ${REDIS_VOLUMES_PATH}:/data
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "${REDIS_PORT}:6379"
    restart: always

  etcd:
    build:
      context: ./dockerfiles/etcd
    environment:
      - TZ=${TZ}
      - ALLOW_NONE_AUTHENTICATION=yes
    ports:
      - "${ETCD_PORT}:2379"
    restart: always

  minio:
    build:
      context: ./dockerfiles/minio
    command: server /data --console-address ":9090" -address ":9080"
    environment:
      - TZ=${TZ}
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    volumes:
      - ${MINIO_VOLUMES_DATA_PATH}:/data
      - ${MINIO_VOLUMES_CONFIG_PATH}:/root/.minio
    ports:
      - "${MINIO_PORT}:9080"
      - "${MINIO_MANAGEMENT_PORT}:9090"
    restart: always
  
  rabbitmq:
    build:
      context: ./dockerfiles/rabbitmq
    environment:
      - TZ=${TZ}
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
      - RABBITMQ_DEFAULT_VHOST=${RABBITMQ_DEFAULT_VHOST}
    ports:
      - "${RABBITMQ_PORT}:5672"
      - "${RABBITMQ_MANAGEMENT_PORT}:15672"
